### ISSUE TITLE
visualization problem of MarkerArray

### ISSUE THREAD

**Issue by dpfzju** [TixiaoShan/traversability_mapping#2]
Hi,
 When I launch the offline.launch, there is a problem like below:
` [ERROR] [1558512470.084778817]: Client [/rviz] wants topic /prm_graph to have datatype/md5sum [visualization_msgs/MarkerArray/90da67007c26525f655c1c269094e39f], but our version has [visualization_msgs/MarkerArray/d155b9ce5188fbaf89745847fd5882d7]. Dropping connection.
 `

**Comment by TixiaoShan** [comment]
You can replace [the two lines](https://github.com/TixiaoShan/traversability_mapping/blob/861d6d19c719c4653c1772b03512118006187047/traversability_mapping/include/utility.h#L58) with the marker header with
```
#include <visualization_msgs/Marker.h>
#include <visualization_msgs/MarkerArray.h>
```
