### ISSUE TITLE
Laser scan and filtered pointcloud of data  is not displayed in RVIZ

### ISSUE THREAD

**Issue by Mr-Xavier** [TixiaoShan/traversability_mapping#3]
Hi, when I run the bag file and launch the package, I am having an error message :
[ WARN] [1573694604.296211630, 1497705852.923826987]: Timed out waiting for transform from base_link to map to become available before running costmap, tf error: Could not find a connection between 'map' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.. canTransform returned after 1.49771e+09 timeout was 0.1.
And laser scan and filtered pointcloud of data  is not displayed in RVIZ.
![rviz_screenshot_2019_11_14-09_23_48](https://user-images.githubusercontent.com/55989363/68819214-5d7b3880-06c2-11ea-9aa7-d250df9c9457.png)
How can I solve this problem?

**Comment by TixiaoShan** [comment]
Hi @Mr-Xavier 
It seems that the tf tree is not connecting ```map``` and ```base_link```. You may need to check the code that publishes this transformation.
