### ISSUE TITLE
Cleaning of previously occupied space in map

### ISSUE THREAD

**Issue by IvanVN** [TixiaoShan/traversability_mapping#8]
Hi,

I've started testing the package and I'm encountering a problem with the capacity of the approach to "clean" previously occupied space (e.g. a moving object) due the way the height is estimated.

I understand that additional measurements from the same previously occupied place will "flatten" the estimated height. However, this will only happen if there are many more readings when the space is empty than when it is occupied. In my case this has never resulted in completely "erasing" the moving object, thus resulting in plenty of non-traversable space.

This issue is critical in cases with large moving obstacles (like cars) or slow moving obstacles, in which readings from different heights for the same spot are going to be a lot, while the readings of the ground when the obstacle is not there anymore are going to be very scarce.

Other approaches solve this problem by raytracing readings from the sensor's frame and cleaning the space between. Is something like this (or other alternatives) planned to be implemented?

Thank you and best regards,

Ivan.

**Comment by TixiaoShan** [comment]
Hi @IvanVN 
What you said above is a problem with the package. If there are no new readings to "refresh" that area, the place where there were moving obstacles is still considered as non-traversable. 

Unfortunately, I have no plan to update the package in the near future. Any contribution would be appreciated.

**Comment by IvanVN** [comment]
Thank you. I'm doing some tests and so far I have had mild success with a "quick and dirty" approach of resetting the elevation estimation when there is a big "jump" in the measurement. I'll PR it for review if I get something usable.

**Comment by TixiaoShan** [comment]
@IvanVN 
Excellent, thanks for the efforts.

**Comment by rock19970106** [comment]
Hi, @IvanVN , Have you solved this problem?

**Comment by IvanVN** [comment]
> Hi, @IvanVN , Have you solved this problem?

No, sorry. I haven't have the time to keep working on this. I have uploaded my fork if you want to check it. There are only a couple of minor changes for the elevation reset, but they can be difficult to track since my clang did a lot of changes in the original code.

https://github.com/tecnalia-advancedmanufacturing-robotics/traversability_mapping/tree/remove-dynamic-obstacles

**Comment by rock19970106** [comment]
> > Hi, @IvanVN , Have you solved this problem?
> 
> No, sorry. I haven't have the time to keep working on this. I have uploaded my fork if you want to check it. There are only a couple of minor changes for the elevation reset, but they can be difficult to track since my clang did a lot of changes in the original code.
> 
> https://github.com/tecnalia-advancedmanufacturing-robotics/traversability_mapping/tree/remove-dynamic-obstacles

okay, thank very much!
